repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-ast
      # - id: check-docstring-first # pydocstyle below?
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
  # black seems to handle trailing commas
  # - repo: https://github.com/asottile/add-trailing-comma
  #   rev: v3.1.0
  #   hooks:
  #     - id: add-trailing-comma
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
